### PR TITLE
Bug Fix

### PR DESCRIPTION
**Pull request by sudospaes**
Hello Again Alireza :)

Bug fix, can't connect after change transmission type from tcp to other types.
If flow is not equal to "" in transmission except tcp, connection will not be made. This problem occurs when we change the transmission from tcp to another type when editing inbound. Also, if tcp itself is alone and without tls and reality, flow must be empty in it.

This code monitors that tcp with tls or reality can only have flow.

### CODE REVIEW

**Comment by alireza0** [comment]
Hello @sudospaes,

Thank you for finding the problem and providing a solution.

Even it is on the shoulder of the person who changed the transmission protocol, but it could be better to fix it in codes and avoid forther peoblems.
In my point of view, it is not good to have it inside DataBase and remove the `flow` each time in restart.
[Here](https://github.com/alireza0/x-ui/blob/main/web/html/xui/inbound_modal.html#L107) you can find proper method in FrontEnd to fix this problem. Then it will be fixed in DB as well.

Suggested code to be added in this method:
```TS
                if (!inModal.inbound.canEnableTlsFlow()) {
                    this.inModal.getClients(this.inModal.inbound.protocol, this.inModal.inbound.settings).forEach(client => {
                        client.flow = "";
                    });
                }
```

**Comment by sudospaes** [comment]
@alireza0 I agree. it is better

**Comment by sudospaes** [comment]
> Hello @sudospaes,
> 
> Thank you for finding the problem and providing a solution.
> 
> Even it is on the shoulder of the person who changed the transmission protocol, but it could be better to fix it in codes and avoid forther peoblems. In my point of view, it is not good to have it inside DataBase and remove the `flow` each time in restart. [Here](https://github.com/alireza0/x-ui/blob/main/web/html/xui/inbound_modal.html#L107) you can find proper method in FrontEnd to fix this problem. Then it will be fixed in DB as well.
> 
> Suggested code to be added in this method:
> 
> ```ts
>                 if (this.inModal.inbound.protocol == Protocols.VLESS && !inModal.inbound.canEnableTlsFlow()) {
>                     this.inModal.inbound.settings.vlesses.forEach(client => {
>                         client.flow = "";
>                     });
>                 }
> ```

I applied your solution in the codes. Also, I fixed another bug that was related to cloning of reality inbounds (after clone publicKey, privateKey, shortIds of the new inbound was still the same as the mother inbound).

**Comment by alireza0** [comment]
Nice Job!
Thank you.

Acctually, I don't agree with changing cert and shortID of duplicated inbound due to:
1. There will be no problem if both inbounds have same data
2. If someone needs same data, it is not easy to change it back ( some people needs to change only the port )
3. It is easy to renew these data in new inbound.
4. Requesting keys is using an additional API call which adds complexity and unstability.

Although in my point of view it is also nice to have this feature ( it is not a bug ), but we should think about different ranges of users. Each feature may make trouble for some types of users, even if it is more useful for others.
I appreciate your efforts and I am always open to hear your reasons and new improvements.

**Comment by sudospaes** [comment]
> Nice Job! Thank you.
> 
> Acctually, I don't agree with changing cert and shortID of duplicated inbound due to:
> 
> 1. There will be no problem if both inbounds have same data
> 2. If someone needs same data, it is not easy to change it back ( some people needs to change only the port )
> 3. It is easy to renew these data in new inbound.
> 4. Requesting keys is using an additional API call which adds complexity and unstability.
> 
> Although in my point of view it is also nice to have this feature ( it is not a bug ), but we should think about different ranges of users. Each feature may make trouble for some types of users, even if it is more useful for others. I appreciate your efforts and I am always open to hear your reasons and new improvements.

I reverted the changes of clone option to the first state. :)

**Pull request merged**
