### PR TITLE
Increse version

### PR DESCRIPTION
**Pull request by alireza0**
Add user's email to remark if exists
Fix false reports
Fix some translations
Fix dockerfile

### CODE REVIEW

**Comment by shahrooz1349** [comment]
Hi Dear Developer @alireza0 
Thanks for developing this nice panel Unfortunately, the panel is not installed

**Comment by alireza0** [comment]
Thank you for your feedback.
Using golang 1.20 may cause some installation problems in old systems specially in CentOS.
Could you please send me more information about your platform and the error you had?

**Comment by alireza0** [comment]
> Hi Dear Developer @alireza0 
> 
> Thanks for developing this nice panel Unfortunately, the panel is not installed

@shahrooz1349 Thank you for your feedback.
Using golang 1.20 may cause some installation problems in old systems specially in CentOS.
Could you please send me more information about your platform and the error you had?

**Comment by shahrooz1349** [comment]
@alireza0 
test in ubuntu 20&22 

Screenshot_20230211_202205_org connectbot_edit_522430062819240
Screenshot_20230211_202234_org connectbot_edit_522413182843201

**Comment by alireza0** [comment]
@shahrooz1349 I have untagged this version as latest version.
Please run `x-ui update` to fix this problem in your servers. I will fix this problem as soon as possible.

**Comment by shahrooz1349** [comment]
ok thank you very much @alireza0

**Comment by alireza0** [comment]
> ok thank you very much @alireza0
@shahrooz1349 
The problem is now fixed. You can run `x-ui update` or `install.sh` script for updating to new version.
Please don't hesitate to inform me about further bugs and suggestions.

Thanks 🙏

**Comment by shahrooz1349** [comment]
The problem is solved, thank you @alireza0

**Pull request merged**
