### PR TITLE
Update x-ui.sh

### PR DESCRIPTION
**Pull request by Enkidu-6**
Change log:

- Made the code less bulky. More code = more potential for bugs and vulnerabilities

- The code is now showing the progress of downloads. Having the progres report allows us to see the errors and rectify them.

- Added a Success / Failure prompt for each download

- Geoip_IR and Geosite_IR do not have a built in support in the Panel. Added a notice that they won't do anything unless
  the users add their own rules manually.

- Solved the inherent problem with wget -O
  
  In the existing script, if a download fails, (i.e. if geofile.dat is not downloaded for any reason, wget -O creates  an empty file by the same name and Xray will crash and won't recover and there's no way to know why.

- Current script gives the user an option to restart or not. It shouldn't be optional. That is fixed.

- Function restart() has already been defined in the script. There's no reason to use several lines for each restart. We're now using the existing function

- Unrelated: I took the liberty to brighten up the colours for the menu. If that's not what you like, please feel free to revert it back.

### CODE REVIEW

**Comment by alireza0** [comment]
Dear @Enkidu-6 ,

Thank you for your enhancements.

It is always good to check the history of files and changes.
Here in #701, you can see my request for optional restarting. I don't agree with you and It should be asked.
Please read it first and then refine your codes.

FYI:
It is planed to use only `Loyalsoldier` and `chocolate4u` packages in next version.

> * Made the code less bulky. More code = more potential for bugs and vulnerabilities

It is the first time I've heard that! That means error handling is also a potential for bug ?!?!

> * The code is now showing the progress of downloads. Having the progres report allows us to see the errors and rectify them.
> * Added a Success / Failure prompt for each download

I agree with this.

> * Geoip_IR and Geosite_IR do not have a built in support in the Panel. Added a notice that they won't do anything unless
>   the users add their own rules manually.

It is going to be supported as I mentioned above.

> * Solved the inherent problem with wget -O

That's great! Thank you :)

> * Current script gives the user an option to restart or not. It shouldn't be optional. That is fixed.
> * Function restart() has already been defined in the script. There's no reason to use several lines for each restart. We're now using the existing function

Please use `confirm_erstart` instead.

> * Unrelated: I took the liberty to brighten up the colours for the menu. If that's not what you like, please feel free to revert it back.

Please revert it, it has high contrast.


Overall, thank you for your nice code. Please fix the code based on my suggestions.

**Comment by Enkidu-6** [comment]
- Removed Iran.dat as it no longer will be supported in the new version.
- Removed the notice about additional 2 files.
- changed restart() to confirm_restart()
- Reverted back to original colours.

> Here in https://github.com/alireza0/x-ui/pull/701, you can see my request for optional restarting.

Sorry about not noticing your request earlier. I've only been following discussions that are in English.

**Comment by alireza0** [comment]
Thanks a lot :)

**Comment by Shellgate** [comment]
خرابش کردین

**Comment by Shellgate** [comment]
کد خیش مشکلی نداشت خرابش کردی

**Comment by Shellgate** [comment]
چیزی که بلد نیستی دست نزن

**Pull request merged**
